/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#dce1ff",
        "inverse-primary": "#1a53d6",
        "primary-fixed-dim": "#b5c4ff",
        "on-tertiary-fixed-variant": "#004e60",
        "surface-container-lowest": "#0c0e13",
        "on-secondary": "#31009a",
        "secondary-fixed-dim": "#cabeff",
        "tertiary": "#4cd6ff",
        "on-background": "#e2e2e9",
        "surface-tint": "#b5c4ff",
        "on-tertiary": "#003543",
        "error": "#ffb4ab",
        "outline": "#8d90a0",
        "tertiary-fixed-dim": "#4cd6ff",
        "on-error-container": "#ffdad6",
        "on-primary": "#00297b",
        "surface-container": "#1e1f25",
        "surface-container-high": "#282a2f",
        "on-surface": "#e2e2e9",
        "inverse-surface": "#e2e2e9",
        "inverse-on-surface": "#2e3036",
        "on-surface-variant": "#c3c5d7",
        "on-primary-fixed-variant": "#003cad",
        "tertiary-container": "#009dc1",
        "on-secondary-fixed": "#1c0062",
        "secondary": "#cabeff",
        "on-primary-fixed": "#00164d",
        "on-primary-container": "#00236d",
        "primary-container": "#648aff",
        "surface-bright": "#37393f",
        "surface-container-highest": "#33353a",
        "on-tertiary-fixed": "#001f28",
        "on-secondary-container": "#b9aaff",
        "on-secondary-fixed-variant": "#4816cb",
        "secondary-container": "#4816cb",
        "background": "#111318",
        "outline-variant": "#434654",
        "primary": "#b5c4ff",
        "tertiary-fixed": "#b7eaff",
        "secondary-fixed": "#e6deff",
        "surface-container-low": "#1a1b21",
        "on-tertiary-container": "#002e3a",
        "on-error": "#690005",
        "surface": "#111318",
        "surface-dim": "#111318",
        "error-container": "#93000a",
        "surface-variant": "#33353a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "20px",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1440px",
        "stack-xl": "64px",
        "margin-mobile": "16px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "gutter": "24px",
        "margin-desktop": "48px"
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
        "label-caps": ["Geist", "monospace"],
        "mono-technical": ["Geist", "monospace"]
      }
    },
  },
  plugins: [],
}
